# Tp1 Señales Eléctricas 2024

## Punto 1

### a

In [2]:
a = 5
A = 7
b = 8
B = 11

print(a)
print(A)
print(B)
print(b)

5
7
11
8


### b

In [3]:
import numpy as np
lista_v =[1,3,7,0]  # esto es una lista
print(lista_v)
print(type(lista_v))
v = np.array(lista_v)
print(v)
print(type(v))

[1, 3, 7, 0]
<class 'list'>
[1 3 7 0]
<class 'numpy.ndarray'>


In [4]:
w = [[5],[6],[2]]
print(w)
print(type(w))
w_array = np.array(w)
print(w_array)
print(type(w_array))

[[5], [6], [2]]
<class 'list'>
[[5]
 [6]
 [2]]
<class 'numpy.ndarray'>


In [5]:
# Ahora lo anterior de otra forma
w_prueba = [5,6,2]
print(w_prueba)
print(type(w_prueba))
w_prueba_array = np.array(w_prueba)
print(w_prueba_array)
print(type(w_prueba_array))
w_prueba_matriz = np.reshape(w_prueba_array, (3,1)) # dar forma w_prueba_array en una matriz de 3 colum y 1 fila
print(w_prueba_matriz)
print(type(w_prueba_matriz))


[5, 6, 2]
<class 'list'>
[5 6 2]
<class 'numpy.ndarray'>
[[5]
 [6]
 [2]]
<class 'numpy.ndarray'>


In [6]:
x = [[0],[-2],[3],[7]]
print(x)
x = np.array(x)
print(x)
x_transpuesto = np.transpose(x)
print(x_transpuesto)

[[0], [-2], [3], [7]]
[[ 0]
 [-2]
 [ 3]
 [ 7]]
[[ 0 -2  3  7]]


### c

In [15]:
# Redefino la variables para tenerlas mas a mano

a = 5
A = 7
b = 8
B = 11
"""
[] hace una lista
[[],[],[]] es una matriz donde en cada [] se pones los elemetos de una fila , parece q numpy trabaja mejor así
"""
v = np.array([[1,3,7,0]]) # doble corchete me dice que es una matriz y el corchete indica los valores de una fila NOTAR no se coloca el tamaño de la matriz
print(v)
w = np.array([[5],[6],[2]])
print(w)
x = np.array([[0],[-2],[3],[7]])
print(x)

[[1 3 7 0]]
[[5]
 [6]
 [2]]
[[ 0]
 [-2]
 [ 3]
 [ 7]]


In [8]:
# a*A
prueba = a*A
print(prueba)

35


[warning] Notar 
que * hace un producto raro, onda es como q multiplica escalarmente una fila por un elento fila de la otra
para hacer el producto matricial se usa @ 


In [9]:
# v*x
prueba = v*x
print(prueba)

prueba = v@x
print(prueba)

[[  0   0   0   0]
 [ -2  -6 -14   0]
 [  3   9  21   0]
 [  7  21  49   0]]
[[15]]


In [10]:
# x*v
prueba = x@v
print(prueba)

[[  0   0   0   0]
 [ -2  -6 -14   0]
 [  3   9  21   0]
 [  7  21  49   0]]


In [11]:
# M=w*v
M = w@v
print(M)

[[ 5 15 35  0]
 [ 6 18 42  0]
 [ 2  6 14  0]]


In [14]:
"""
 v*w no es valido con @ porque v es 1x4 y w es 3x1 no se puede hacer la multiplicacion de matrices
 sin embargo hacelo con * se si puede porque hace un producto raro
 """
prueba = v @ w
print(prueba)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [ ]:
# N=M*x
N = M@x
print(N)

[[75]
 [90]
 [30]]


In [ ]:
# P=w'*M, la comilla es la transpuesta
P = np.transpose(w) @ M
print(P)

[[ 65 195 455   0]]


### d

In [24]:
# variable[numero de fila][numero de columna]
# otra forma es usar .item(numero de elemento) se cuenta de izq a derecha y hacia abajo
# notar el indice empieza en 0

print(v)
print(v[0][0])
print(v.item(2))
print(M)
print(M[2][3])
print(M.item(10))

[[1 3 7 0]]
1
7
[[ 5 15 35  0]
 [ 6 18 42  0]
 [ 2  6 14  0]]
0
14
