# Tp 1 

## punto 2
### a

In [1]:
import math
import numpy as np

In [2]:
a = 5
A = 7
b = 8
B = 11

v = np.array([[1,3,7,0]])
print(v)
w = np.array([[5],[6],[2]])
print(w)
x = np.array([[0],[-2],[3],[7]])
print(x)

[[1 3 7 0]]
[[5]
 [6]
 [2]]
[[ 0]
 [-2]
 [ 3]
 [ 7]]


Las funciones sobre matrices se puedn trabajar sobre una fila, seguro tmb sobre columna pero nose como hacer referencia a una columna

In [13]:
valor_max_w_fila3 = np.max(w[2])
print(valor_max_w_fila1)

valor_max_w = np.max(w)
print(valor_max_w)

valor_min_w = np.min(w)
print(valor_min_w)

valor_medio_w = np.mean(w)
print(valor_medio_w)

valor_medio_w_fila2 = np.mean(w[1])
print(valor_medio_w_fila2)

2
6
2
4.333333333333333
6.0


### b

In [21]:
?? round
var_1 = 5.1234567
print(round(var_1))
print(round(var_1,3))

5
5.123


Signature:  round(number, ndigits=None)
Docstring:
Round a number to a given precision in decimal digits.

The return value is an integer if ndigits is omitted or None.  Otherwise
the return value has the same type as the number.  ndigits may be negative.
Type:      builtin_function_or_method

In [22]:
# redonde al entero superior
?? math.ceil
print(math.ceil(var_1))

6


Signature:  math.ceil(x, /)
Docstring:
Return the ceiling of x as an Integral.

This is the smallest integer >= x.
Type:      builtin_function_or_method

In [24]:
?? abs

var_2 = -4.12345
print(abs(var_1))
print(abs(var_2))


5.1234567
4.12345


Signature:  abs(x, /)
Docstring: Return the absolute value of the argument.
Type:      builtin_function_or_method

## Punto 3
### a

In [27]:
import matplotlib.pyplot as plt
import numpy as np

In [32]:
positivos = np.linspace(start=0, stop=10, num=int((10-0+1)/1), dtype='int')
print(type(positivos))
print(positivos)

<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10]


In [49]:
enteros = np.linspace(start=-4, stop=2, num=int((2+4+1)/1)) 
print(enteros)
enteros = np.linspace(start=-4, stop=2, num=int((2+4+1)/1), dtype='int') 
print(enteros)
# si se pone la cant de elementos mal elminia uno si es menor o agrega uno extra si es mayor


[-4. -3. -2. -1.  0.  1.  2.]
[-4 -3 -2 -1  0  1  2]


In [41]:
multiplos = np.arange(start=0, stop=14, step=3)
print(multiplos)
# notar que llega hasta 12, xq el siguiente es 15 y es mayor a 14

[ 0  3  6  9 12]


In [48]:
reverso = np.arange(start=7, stop=2, step= -1.5, dtype='int')
print(reverso)
reverso = np.arange(start=7, stop=2, step= -1.5)
print(reverso)

[7 5 3 1]
[7.  5.5 4.  2.5]
